### ISSUE TITLE
Issues in running the program

### ISSUE THREAD

**Issue by awakedonut17** [makiisthenes/TiktokAutoUploader#21]
Hello, 
when I try to run the program i get these errors:
Traceback (most recent call last):
  File "C:\Users\Owner\Documents\GitHub\TiktokAutoUploader\main.py", line 1, in <module>
    from TiktokBot import TiktokBot
  File "C:\Users\Owner\Documents\GitHub\TiktokAutoUploader\TiktokBot.py", line 1, in <module>
    from Upload import Upload
  File "C:\Users\Owner\Documents\GitHub\TiktokAutoUploader\Upload.py", line 3, in <module>
    from Bot import Bot
  File "C:\Users\Owner\Documents\GitHub\TiktokAutoUploader\Bot.py", line 1, in <module>
    from selenium.webdriver.common.by import By
ModuleNotFoundError: No module named 'selenium'

do you know what could be causing this?
thanks!

**Comment by ErinTomorri** [comment]
you dont have the selenium package downloaded

**Comment by osvaldai** [comment]
Major error, cannot find the file upload button, please update getVideoUploadInput() in Bot.py how fix it problem ?

**Comment by ErinTomorri** [comment]
The upload feature for direct uploads doesn't work.

**Comment by ErinTomorri** [comment]
Then change the class names in the bot.py file, you can change them by getting them in your inspect element of chrome. This should fix the problem

**Comment by osvaldai** [comment]
> 

I changed the names of the elements in the code but it did not work

**Comment by ErinTomorri** [comment]
Post your code I can try to fix it. I got mine to work after playing around with it

**Comment by osvaldai** [comment]
> Post your code I can try to fix it. I got mine to work after playing around with it

i use this code https://github.com/makiisthenes/TiktokAutoUploader/tree/master/v2

**Comment by thanhtung0512** [comment]
i had the same issue !!!

> Major error, cannot find the file upload button, please update getVideoUploadInput() in Bot.py how fix it problem ?

**Comment by darkzbaron** [comment]
same here
