### ISSUE TITLE
undetected_chromedriver.v2

### ISSUE THREAD

**Issue by johnbulau** [makiisthenes/TiktokAutoUploader#44]
C:\Users\haine\Downloads\TiktokAutoUploader-master>python main.py
Traceback (most recent call last):
  File "C:\Users\haine\Downloads\TiktokAutoUploader-master\main.py", line 1, in <module>
    from TiktokBot import TiktokBot
  File "C:\Users\haine\Downloads\TiktokAutoUploader-master\TiktokBot.py", line 1, in <module>
    from Upload import Upload
  File "C:\Users\haine\Downloads\TiktokAutoUploader-master\Upload.py", line 5, in <module>
    from Browser import Browser
  File "C:\Users\haine\Downloads\TiktokAutoUploader-master\Browser.py", line 1, in <module>
    import undetected_chromedriver.v2 as uc
ModuleNotFoundError: No module named 'undetected_chromedriver.v2'

C:\Users\haine\Downloads\TiktokAutoUploader-master>

**Comment by johnbulau** [comment]
please help me

**Comment by makiisthenes** [comment]
Please add this library to your environment, 
https://pypi.org/project/undetected-chromedriver/

Command is: 
pip install undetected-chromedriver
