### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by zerofishy** [makiisthenes/TiktokAutoUploader#55]
Hi,i have a new error bro, first get this errors today

PS C:\Users\SystemX\Downloads\TiktokAutoUploader-main> python cli.py login -n 1234             
User not found on system.
Traceback (most recent call last):
  File "C:\Users\SystemX\Downloads\TiktokAutoUploader-main\cli.py", line 47, in <module>                
    tiktok.login(login_name)                                                                            
  File "C:\Users\SystemX\Downloads\TiktokAutoUploader-main\tiktok_uploader\tiktok.py", line 23, in login
    browser = Browser.get()                                                                             
              ^^^^^^^^^^^^^                                                                             
  File "C:\Users\SystemX\Downloads\TiktokAutoUploader-main\tiktok_uploader\Browser.py", line 20, in get
    Browser.__instance = Browser()
                         ^^^^^^^^^
  File "C:\Users\SystemX\Downloads\TiktokAutoUploader-main\tiktok_uploader\Browser.py", line 32, in __init__
    self._driver = uc.Chrome(options=options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\SystemX\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

![image](https://github.com/makiisthenes/TiktokAutoUploader/assets/75533720/d6eac652-f3cf-4cb2-881a-1f2498fb681d)

**Comment by makiisthenes** [comment]
Make sure chrome is installed and you have the latest version, as there is reliance on chrome drivers in order to login. I will make a help file for this issue.

**Comment by zerofishy** [comment]
ty now

**Comment by Vorato** [comment]
I get the same error. I have chrome installed and updated to the latest version. Perhaps an in-depth startup tutorial would set this straight for people.
