### ISSUE TITLE
issue after uploading the video 

### ISSUE THREAD

**Issue by PluttoX** [makiisthenes/TiktokAutoUploader#59]
(tictokbotenv) C:\Users\raosa\Desktop\Tictok Bot\TiktokAutoUploader-main\TiktokAutoUploader-main>python cli.py upload --user demmo -yt "https://www.youtube.com/shorts/IksiReLYdJY" -t "My video title"
Detected Youtube Video...
Starting Download for Video...
User successfully logged in.
### Tiktok Datacenter Assigned: alisg
Uploading video...
Traceback (most recent call last):
  File "C:\Users\raosa\Desktop\Tictok Bot\TiktokAutoUploader-main\TiktokAutoUploader-main\cli.py", line 76, in <module>
    tiktok.upload_video(args.users, args.video,  args.title, args.schedule, args.comment, args.duet, args.stitch, args.visibility, args.brandorganic, args.brandcontent, args.ailabel, args.proxy)
  File "C:\Users\raosa\Desktop\Tictok Bot\TiktokAutoUploader-main\TiktokAutoUploader-main\tiktok_uploader\tiktok.py", line 176, in upload_video
    xbogus = subprocess_jsvmp(os.path.join(os.getcwd(), "tiktok_uploader", "./signer.js"), user_agent,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raosa\Desktop\Tictok Bot\TiktokAutoUploader-main\TiktokAutoUploader-main\tiktok_uploader\bot_utils.py", line 9, in subprocess_jsvmp
    proc = subprocess.Popen(['node', js, url, user_agent], stdout=subprocess.PIPE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raosa\pyver\py3115\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\raosa\pyver\py3115\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by makiisthenes** [comment]
You must have node installed, please follow instructions in link: https://nodejs.org/en/download
