### ISSUE TITLE
Seems to be endlessly idling on upload

### ISSUE THREAD

**Issue by cooldude3828** [makiisthenes/TiktokAutoUploader#62]
error: XDG_RUNTIME_DIR not set in the environment.
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
User successfully logged in.
Tiktok Datacenter Assigned: useast5
Uploading video...
[-] Waiting for TikTok to process video...
[-] Waiting for TikTok to process video...
[-] Waiting for TikTok to process video...
[-] Waiting for TikTok to process video...
[-] Waiting for TikTok to process video...
[-] Waiting for TikTok to process video...
[-] Waiting for TikTok to process video...
[-] Waiting for TikTok to process video...
page.evaluate: TypeError: Cannot read properties of undefined (reading 'sign')
    at generateSignature (eval at evaluate (:226:30), <anonymous>:3:42)
    at eval (eval at evaluate (:226:30), <anonymous>:1:1)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:226:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at Signer.sign (/content/TiktokAutoUploader/tiktok_uploader/tiktok-signature/index.js:121:33)
    at main (/content/TiktokAutoUploader/tiktok_uploader/tiktok-signature/browser.js:11:31)

**Comment by hypefi** [comment]
same error here too !

**Comment by makiisthenes** [comment]
Will fix

**Comment by webees** [comment]
Please upload via proxy ip
