### ISSUE TITLE
Traceback while Uploading video...

### ISSUE THREAD

**Issue by PandaDouxYT** [makiisthenes/TiktokAutoUploader#80]
User successfully logged in.
Tiktok Datacenter Assigned: useast2a
Uploading video...
Traceback (most recent call last):
  File "C:\Users\antho\Desktop\TikShort\TiktokAutoUploader-main\cli.py", line 76, in <module>
    tiktok.upload_video(args.users, args.video,  args.title, args.schedule, args.comment, args.duet, args.stitch, args.visibility, args.brandorganic, args.brandcontent, args.ailabel, args.proxy)
  File "C:\Users\antho\Desktop\TikShort\TiktokAutoUploader-main\tiktok_uploader\tiktok.py", line 193, in upload_video
    signatures = subprocess_jsvmp(os.path.join(os.getcwd(), "tiktok_uploader", "tiktok-signature", "browser.js"), user_agent, f"https://www.tiktok.com/api/v1/web/project/post/?app_name=tiktok_web&channel=tiktok_web&device_platform=web&aid=1988&msToken={mstoken}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\Desktop\TikShort\TiktokAutoUploader-main\tiktok_uploader\bot_utils.py", line 9, in subprocess_jsvmp
    proc = subprocess.Popen(['node', js, url, user_agent], stdout=subprocess.PIPE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\antho\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

**Comment by thanamesleo** [comment]
I had the same issue. i was using Python 3.12, i switched to Python 3.9 and it worked (at least this error was resolved)
