### ISSUE TITLE
failed at upload stage ubuntu 20.04

### ISSUE THREAD

**Issue by Sonder1738** [makiisthenes/TiktokAutoUploader#82]
```
Tiktok Datacenter Assigned: alisg
Uploading video...
/TiktokAutoUploader/tiktok_uploader/tiktok-signature/index.js:6
  userAgent =
            ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/TiktokAutoUploader/tiktok_uploader/tiktok-signature/browser.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Traceback (most recent call last):
  File "/TiktokAutoUploader/cli.py", line 76, in <module>
    tiktok.upload_video(args.users, args.video,  args.title, args.schedule, args.comment, args.duet, args.stitch, args.visibility, args.brandorganic, args.brandcontent, args.ailabel, args.proxy)
  File "/TiktokAutoUploader/tiktok_uploader/tiktok.py", line 192, in upload_video
    tt_output = json.loads(signatures)["data"]
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I am running the script in Ubuntu and it fails at the upload  stage. I've tried installing chrome via 
```
sudo apt-get install libxss1 libappindicator1 libindicator7
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome*.deb
```

**Comment by maximeschwab** [comment]
I encountered the same issue. Did you find any workaround?
