### ISSUE TITLE
Fails at Login ("User not found on System") detailed error in description

### ISSUE THREAD

**Issue by Pectr0n** [makiisthenes/TiktokAutoUploader#91]
Running 'python3 cli.py login -n username' on pop-os gets me this error:

User not found on system.
Traceback (most recent call last):
  File "/media/jannis/pi-stick/TiktokAutoUploader/cli.py", line 47, in <module>
    tiktok.login(login_name)
  File "/media/jannis/pi-stick/TiktokAutoUploader/tiktok_uploader/tiktok.py", line 29, in login
    browser = Browser.get()
  File "/media/jannis/pi-stick/TiktokAutoUploader/tiktok_uploader/Browser.py", line 19, in get
    Browser.__instance = Browser()
  File "/media/jannis/pi-stick/TiktokAutoUploader/tiktok_uploader/Browser.py", line 32, in __init__
    self._driver = uc.Chrome(options=options)
  File "/media/jannis/pi-stick/TiktokAutoUploader/venv/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 372, in __init__
    options.binary_location = (
  File "/media/jannis/pi-stick/TiktokAutoUploader/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/options.py", line 52, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String

**Comment by makiisthenes** [comment]
Have you installed chromedriver?
