### ISSUE TITLE
page.evaluate: TypeError: Cannot read properties of undefined (reading 'sign')

### ISSUE THREAD

**Issue by daytradertools** [makiisthenes/TiktokAutoUploader#92]
Every second upload or so I run into the following issue:

`page.evaluate: TypeError: Cannot read properties of undefined (reading 'sign')
    at generateSignature (eval at evaluate (:234:30), <anonymous>:3:42)
    at eval (eval at evaluate (:234:30), <anonymous>:1:1)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:234:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at Signer.sign (K:\Tools\TiktokAutoUploader\tiktok_uploader\tiktok-signature\index.js:121:33)
    at main (K:\Tools\TiktokAutoUploader\tiktok_uploader\tiktok-signature\browser.js:11:31)`

Sometime ist works. Any ideas?

**Comment by robbwright** [comment]
I'm getting this error too. Sometimes retrying it will push the video through, sometimes not. Seems to be a server-side issue.

It would be helpful to trap this error and retry - maybe have a "retry #" in the config file
